import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'

export default  function Home() {
  const [Datos, setData] = useState([])

  useEffect( ()=> {
    async function fetchData() {
      console.log("Buscando...")
      const rest = await fetch("http://localhost:3000/api/hello")
      const data = await rest.json()
      console.log(data)
      setData(data)
    }
    fetchData();    

  }, [])

//   const Listar = Data_ref.current.list.map((item) =>
//   <p key={item} value={item}>{item}</p>
// );

 return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        {/* <div className={styles.description}>
          {Data_ref === [] ? <div></div> : Listar}
          </div> */}
      </main>
    </>
  )
}
